parameters:
#    i_sportis_test.example.class: ISportis\TestBundle\Example

services:
#    i_sportis_test.example:
#        class: %i_sportis_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
